export default {
  TECHNICAL_SUPPORT: 'TECHNICAL_SUPPORT',
  ADMIN_MASTER: 'ADMIN_MASTER',
  ADMIN_CHURCH: 'ADMIN_CHURCH',
  ADMIN_MODULE: 'ADMIN_MODULE',
  ASSISTANT: 'ASSISTANT',
  MEMBER: 'MEMBER',
}
