export const subjects = {
  ROOT: 'ROOT',

  ADMIN_USERS: 'ADMIN_USERS',

  ADMIN_USERS_ADMIN_MASTER: 'ADMIN_USERS_ADMIN_MASTER',
  ADMIN_USERS_ADMIN_CHURCH: 'ADMIN_USERS_ADMIN_CHURCH',
  ADMIN_USERS_ADMIN_MODULE: 'ADMIN_USERS_ADMIN_MODULE',
  ADMIN_USERS_ADMIN_ASSISTANT: 'ADMIN_USERS_ADMIN_ASSISTANT',
  ADMIN_USERS_ADMIN_MEMBER: 'ADMIN_USERS_ADMIN_MEMBER',

  FINANCE_MODULE: 'FINANCE_MODULE',
  STORE_MODULE: 'STORE_MODULE',
  GROUPS_MODULE: 'GROUPS_MODULE',
  MEMBERSHIP_MODULE: 'MEMBERSHIP_MODULE',
  SCHEDULE_MODULE: 'SCHEDULE_MODULE',
  PATRIMONY_MODULE: 'PATRIMONY_MODULE',
  USERS_MODULE: 'USERS_MODULE',

  MEMBERSHIP_MODULE_CHURCH: 'MEMBERSHIP_MODULE_CHURCH',
  MEMBERSHIP_MODULE_CHURCH_DETAILS: 'MEMBERSHIP_MODULE_CHURCH_DETAILS',

  MEMBERSHIP_MODULE_CHURCH_ADMIN_MASTER: 'MEMBERSHIP_MODULE_CHURCH_ADMIN_MASTER',
  MEMBERSHIP_MODULE_CHURCH_ADMIN_MASTER_DETAILS: 'MEMBERSHIP_MODULE_CHURCH_ADMIN_MASTER_DETAILS',
  MEMBERSHIP_MODULE_CHURCH_ADMIN_MASTER_IMAGE: 'MEMBERSHIP_MODULE_CHURCH_ADMIN_MASTER_IMAGE',

  MEMBERSHIP_MODULE_CHURCH_ADMIN_CHURCH: 'MEMBERSHIP_MODULE_CHURCH_ADMIN_CHURCH',
  MEMBERSHIP_MODULE_CHURCH_ADMIN_CHURCH_DETAILS: 'MEMBERSHIP_MODULE_CHURCH_ADMIN_CHURCH_DETAILS',
  MEMBERSHIP_MODULE_CHURCH_ADMIN_CHURCH_IMAGE: 'MEMBERSHIP_MODULE_CHURCH_ADMIN_CHURCH_IMAGE',

  MEMBERSHIP_MODULE_CHURCH_ADMIN_MODULE: 'MEMBERSHIP_MODULE_CHURCH_ADMIN_MODULE',
  MEMBERSHIP_MODULE_CHURCH_ADMIN_MODULE_DETAILS: 'MEMBERSHIP_MODULE_CHURCH_ADMIN_MODULE_DETAILS',

  MEMBERSHIP_MODULE_CHURCH_ASSISTANT: 'MEMBERSHIP_MODULE_CHURCH_ASSISTANT',
  MEMBERSHIP_MODULE_CHURCH_ASSISTANT_DETAILS: 'MEMBERSHIP_MODULE_CHURCH_ASSISTANT_DETAILS',

  MEMBERSHIP_MODULE_CHURCH_ADMIN_MASTER_USER_RELATIONSHIP: 'MEMBERSHIP_MODULE_CHURCH_ADMIN_MASTER_USER_RELATIONSHIP',
  MEMBERSHIP_MODULE_CHURCH_ADMIN_CHURCH_USER_RELATIONSHIP: 'MEMBERSHIP_MODULE_CHURCH_ADMIN_CHURCH_USER_RELATIONSHIP',

  MEMBERSHIP_MODULE_MEMBERS: 'MEMBERSHIP_MODULE_MEMBERS',
  MEMBERSHIP_MODULE_MEMBERS_DETAILS: 'MEMBERSHIP_MODULE_MEMBERS_DETAILS',

  MEMBERSHIP_MODULE_MEMBERS_ADMIN_MASTER: 'MEMBERSHIP_MODULE_MEMBERS_ADMIN_MASTER',
  MEMBERSHIP_MODULE_MEMBERS_ADMIN_MASTER_DETAILS: 'MEMBERSHIP_MODULE_MEMBERS_ADMIN_MASTER_DETAILS',

  MEMBERSHIP_MODULE_MEMBERS_ADMIN_CHURCH: 'MEMBERSHIP_MODULE_MEMBERS_ADMIN_CHURCH',
  MEMBERSHIP_MODULE_MEMBERS_ADMIN_CHURCH_DETAILS: 'MEMBERSHIP_MODULE_MEMBERS_ADMIN_CHURCH_DETAILS',

  MEMBERSHIP_MODULE_MEMBERS_ADMIN_MODULE: 'MEMBERSHIP_MODULE_MEMBERS_ADMIN_MODULE',
  MEMBERSHIP_MODULE_MEMBERS_ADMIN_MODULE_DETAILS: 'MEMBERSHIP_MODULE_MEMBERS_ADMIN_MODULE_DETAILS',

  MEMBERSHIP_MODULE_MEMBERS_ASSISTANT: 'MEMBERSHIP_MODULE_MEMBERS_ASSISTANT',
  MEMBERSHIP_MODULE_MEMBERS_ASSISTANT_DETAILS: 'MEMBERSHIP_MODULE_MEMBERS_ASSISTANT_DETAILS',

  STORE_MODULE_DEPARTMENTS: 'STORE_MODULE_DEPARTMENTS',
  STORE_MODULE_DEPARTMENTS_STATUS: 'STORE_MODULE_DEPARTMENTS_STATUS',

  STORE_MODULE_CATEGORIES: 'STORE_MODULE_CATEGORIES',
  STORE_MODULE_CATEGORIES_STATUS: 'STORE_MODULE_CATEGORIES_STATUS',

  UNIQUE_CODE_PREFIXES: 'UNIQUE_CODE_PREFIXES',

  STORE_MODULE_PRODUCTS: 'STORE_MODULE_PRODUCTS',
  STORE_MODULE_PRODUCTS_STATUS: 'STORE_MODULE_PRODUCTS_STATUS',

  STORE_MODULE_SALES: 'STORE_MODULE_SALES',

  USERS_ADMIN_MASTER_UPDATE_STATUS: 'USERS_ADMIN_MASTER_UPDATE_STATUS',
  USERS_ADMIN_CHURCH_UPDATE_STATUS: 'USERS_ADMIN_CHURCH_UPDATE_STATUS',
  USERS_ADMIN_MODULE_UPDATE_STATUS: 'USERS_ADMIN_MODULE_UPDATE_STATUS',
}

export const actions = {
  VIEW: 'VIEW',
  INSERT: 'INSERT',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
}
