export const subjects = {
  ROOT: 'ROOT',

  ADMIN_USERS: 'ADMIN_USERS',
  TEAM_USERS: 'TEAM_USERS',
  PROJECTS: 'PROJECTS',
  NOTES: 'NOTES',
  TAGS: 'TAGS',

  PROJECTS_ADMIN_MASTER: 'PROJECTS_ADMIN_MASTER',

  PROJECTS_ADMIN_MASTER_TEAM_USER: 'PROJECTS_ADMIN_MASTER_TEAM_USER',
  PROJECTS_PROJECT_MANAGER_TEAM_USER: 'PROJECTS_PROJECT_MANAGER_TEAM_USER',
  PROJECTS_TEAM_LEADER_TEAM_USER: 'PROJECTS_TEAM_LEADER_TEAM_USER',

  PROJECTS_ADMIN_MASTER_TAGS: 'PROJECTS_ADMIN_MASTER_TAGS',
  PROJECTS_PROJECT_MANAGER_TAGS: 'PROJECTS_PROJECT_MANAGER_TAGS',
  PROJECTS_TEAM_LEADER_TAGS: 'PROJECTS_TEAM_LEADER_TAGS',

  PROJECTS_ADMIN_MASTER_ICON: 'PROJECTS_ADMIN_MASTER_ICON',
  PROJECTS_PROJECT_MANAGER_ICON: 'PROJECTS_PROJECT_MANAGER_ICON',
  PROJECTS_TEAM_LEADER_ICON: 'PROJECTS_TEAM_LEADER_ICON',

  PROJECTS_ADMIN_MASTER_INFO: 'PROJECTS_ADMIN_MASTER_INFO',
  PROJECTS_PROJECT_MANAGER_INFO: 'PROJECTS_PROJECT_MANAGER_INFO',
  PROJECTS_TEAM_LEADER_INFO: 'PROJECTS_TEAM_LEADER_INFO',
}

export const actions = {
  VIEW: 'VIEW',
  INSERT: 'INSERT',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
}
